# configuration for the ingress-controller
ingressController:
  # default of 1 should be enough because it only will prevent the creation of new
  # ALB rules if the pod is not present in case of updates or outages
  replicas: 1
  # REQUIRED setting for kube-ingress-aws-controller
  # if not set kube-ingress-aws-controller won't be able create ALBs at all
  awsRegion: ""
  # image settings for kube-ingress-aws-controller
  image:
    repository: registry.opensource.zalan.do/teapot/kube-ingress-aws-controller
    tag: v0.6.10
    pullPolicy: IfNotPresent

# configuration for kube2iam
kube2iam:
  # ARN kube2iam should assign to Skipper and the ingress controller
  # to create ALBs within AWS
  awsArn: ""

# Configuration for resource alocation of the daemonset
resources:
  limits:
   cpu: 200m
   memory: 200Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

# Configuration for Kubernetes RBAC
rbac:
  # enable RBAC support
  create: false
  # name of the ServiceAccount
  svcAccountName: aws-ingress-controller
  # Name of the ClusterRole for Skipper
  clusterRoleName: aws-ingress-controller
  # Name of the ClusterRoleBinding
  clusterRoleBindingName: aws-ingress-controller
