# Default values for kube-ingress-aws-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

skipper:
  logLevel: INFO
  updateStrategy:
    type: RollingUpdate
  endpoint:
    name: skipper
    internalPort: 9999
    externalPort: 9999
  image:
    repository: registry.opensource.zalan.do/pathfinder/skipper
    tag: v0.9.202
    pullPolicy: IfNotPresent

ingressController:
  replicas: 1
  awsRegion: ""
  image:
    repository: registry.opensource.zalan.do/teapot/kube-ingress-aws-controller
    tag: v0.6.8 
    pullPolicy: IfNotPresent

kube2iam:
  enable: false
  awsArn: ""

prometheusOperator:
  jobLabel: kube-ingress-aws-controller
  monitorName: kube-aws-ingress-metrics
  namespace: monitoring
  enable: false
  scrapeInterval: 30s
  labels:
    prometheus: kube-prometheus
  endpoint:
    name: skipper-metrics
    externalPort: 9911

resources:
  limits:
   cpu: 200m
   memory: 200Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

rbac:
  enable: false
  svcAccountName: aws-ingress-controller
  svcAccountNamespace: kube-system
  clusterRoleName: aws-ingress-controller
  clusterRoleBindingName: aws-ingress-controller
