{{- with .Values.rbac }}
{{- if .enable }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ .clusterRoleBindingName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .clusterRoleName }}
subjects:
- kind: ServiceAccount
  name: aws-ingress-controller
  namespace: kube-system
{{- end }}
{{- end }}